included:

excluded:
- Pods
- IssueTrackerTests

disabled_rules:
- trailing_whitespace
- identifier_name
- todo
- function_parameter_count
- line_length
- type_name

force_cast: warning
line_length: 250
